import path from 'path'
import pathUtil from 'path'
import { IFieldTemplateItem, ISchemaTemplateItem } from '@sprucelabs/schema'
import {
	IDefinitionBuilderTemplateItem,
	IValueTypes,
} from '@sprucelabs/spruce-templates'
import { LATEST_HANDLEBARS } from '../constants'
import SpruceError from '../errors/SpruceError'
import diskUtil from '../utilities/disk.utility'
import namesUtil from '../utilities/names.utility'
import versionUtil from '../utilities/version.utility'
import AbstractGenerator, { GenerationResults } from './AbstractGenerator'

export interface IGenerateSchemaTypesOptions {
	fieldTemplateItems: IFieldTemplateItem[]
	schemaTemplateItems: ISchemaTemplateItem[]
}

export interface IGenerateFieldTypesOptions {
	fieldTemplateItems: IFieldTemplateItem[]
}

export interface IGenerateSchemaTypesOptions {
	fieldTemplateItems: IFieldTemplateItem[]
	schemaTemplateItems: ISchemaTemplateItem[]
	valueTypes: IValueTypes
	namespacePrefix?: string
}

export interface ISchemaTypesGenerationStage {
	name: string
	errors: SpruceError[]
	successfulSchemas: number
	successfulFields: number
}
export default class SchemaGenerator extends AbstractGenerator {
	private readonly fieldTemplates: {
		filename: string
		templateFuncName: 'fieldsTypes' | 'fieldClassMap' | 'fieldTypeEnum'
		description: string
	}[] = [
		{
			filename: 'fields.types.ts',
			templateFuncName: 'fieldsTypes',
			description:
				'All the interfaces generated for every type of schema field (text, number, address, etc)',
		},
		{
			filename: 'fieldClassMap.ts',
			templateFuncName: 'fieldClassMap',
			description:
				'An object that is injected into the FieldFactory and ensures 3rd party fields are integrated',
		},
		{
			filename: 'fieldTypeEnum.ts',
			templateFuncName: 'fieldTypeEnum',
			description:
				'This is your autogenerated, skill-specific enumeration of all the fields you have access to',
		},
	]

	public async generateBuilder(
		destinationDir: string,
		options: IDefinitionBuilderTemplateItem & { enableVersioning?: boolean }
	): Promise<GenerationResults> {
		const filename = `${options.nameCamel}.builder.ts`

		const resolvedBuilderDestination =
			options.enableVersioning === false
				? pathUtil.resolve(destinationDir, filename)
				: versionUtil.resolveNewLatestPath(
						destinationDir,
						LATEST_HANDLEBARS,
						filename
				  )

		if (diskUtil.doesFileExist(resolvedBuilderDestination)) {
			throw new SpruceError({
				// @ts-ignore
				code: 'SCHEMA_EXISTS',
				name: options.nameCamel,
				errorBuilderDestinationDir: destinationDir,
				friendlyMessage: 'This schema already exists!',
			})
		}

		const builderContent = this.templates.definitionBuilder(options)

		const results = this.writeFileIfChangedMixinResults(
			resolvedBuilderDestination,
			builderContent,
			'The file from which all types, interfaces, and protocols will be generated'
		)

		return results
	}

	public async generateFieldTypes(
		destinationDir: string,
		options: IGenerateFieldTypesOptions
	): Promise<GenerationResults> {
		const { fieldTemplateItems } = options

		let results: GenerationResults = []

		this.fieldTemplates.forEach((fileAndFunc) => {
			const { filename, templateFuncName, description } = fileAndFunc

			const resolvedDestination = path.join(destinationDir, 'fields', filename)

			const contents = this.templates[templateFuncName]({
				fieldTemplateItems,
			})

			results = this.writeFileIfChangedMixinResults(
				resolvedDestination,
				contents,
				description,
				results
			)
		})

		return results
	}

	public generateSchemaTypes(
		destinationDirOrFilename: string,
		options: IGenerateSchemaTypesOptions
	): GenerationResults {
		const { fieldTemplateItems, schemaTemplateItems, valueTypes } = options
		const resolvedTypesDestination = this.resolveFilename(
			destinationDirOrFilename,
			'schemas.types.ts'
		)

		let results: GenerationResults = []

		const schemaTypesContents = this.templates.schemasTypes({
			schemaTemplateItems,
			fieldTemplateItems,
			valueTypes,
			namespacePrefix: options.namespacePrefix,
		})

		results = this.writeFileIfChangedMixinResults(
			resolvedTypesDestination,
			schemaTypesContents,
			'The interfaces for every schema'
		)

		results.push(
			...this.generateAllDefinitions(
				pathUtil.dirname(resolvedTypesDestination),
				{ ...options, typesFile: resolvedTypesDestination }
			)
		)

		return results
	}

	private generateAllDefinitions(
		destinationDir: string,
		options: IGenerateSchemaTypesOptions & { typesFile?: string }
	): GenerationResults {
		const results: GenerationResults = []

		options.schemaTemplateItems.map((item) => {
			results.push(
				...this.generateDefinition(destinationDir, { ...options, ...item })
			)
		})

		return results
	}

	public generateDefinition(
		destinationDir: string,
		options: {
			schemaTemplateItems: ISchemaTemplateItem[]
			fieldTemplateItems: IFieldTemplateItem[]
			valueTypes: IValueTypes
			typesFile?: string
		} & ISchemaTemplateItem
	) {
		const {
			schemaTemplateItems,
			fieldTemplateItems,
			valueTypes,
			...item
		} = options

		const resolvedDestination = path.join(
			destinationDir,
			namesUtil.toCamel(options.namespace),
			options.definition.version ?? '',
			`${item.id}.definition.ts`
		)

		let typesFile = options.typesFile
			? pathUtil.relative(
					pathUtil.dirname(resolvedDestination),
					options.typesFile
			  )
			: undefined

		if (typesFile) {
			typesFile = typesFile.replace(pathUtil.extname(typesFile), '')
		}

		const definitionContents = this.templates.definition({
			...item,
			schemaTemplateItems,
			fieldTemplateItems,
			valueTypes,
			typesFile,
		})

		return this.writeFileIfChangedMixinResults(
			resolvedDestination,
			definitionContents,
			`The definition of ${item.nameReadable}`
		)
	}

	public async generateValueTypes(
		destinationDir: string,
		options: {
			schemaTemplateItems: ISchemaTemplateItem[]
			fieldTemplateItems: IFieldTemplateItem[]
		}
	): Promise<GenerationResults> {
		const contents = this.templates.valueTypes(options)
		const destination = pathUtil.join(destinationDir, 'tmp', 'valueType.tmp.ts')

		return this.writeFileIfChangedMixinResults(
			destination,
			contents,
			'For constructing what goes to the right of the : after each property in the interface.'
		)
	}
}
