const onTestFileResult = (fileName: string) => ({
	status: 'onTestFileResult',
	test: {
		context: {
			config: {
				automock: false,
				cache: true,
				cacheDirectory:
					'/private/var/folders/qw/v2bfr0c94bn37vclwvcltsj40000gn/T/jest_dx',
				clearMocks: false,
				coveragePathIgnorePatterns: ['/node_modules/'],
				cwd: '/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api',
				detectLeaks: false,
				detectOpenHandles: false,
				errorOnDeprecated: false,
				extraGlobals: [],
				forceCoverageMatch: [],
				globals: {},
				haste: {
					computeSha1: false,
					throwOnModuleCollision: false,
				},
				injectGlobals: true,
				moduleDirectories: ['node_modules'],
				moduleFileExtensions: ['js', 'json', 'jsx', 'ts', 'tsx', 'node'],
				moduleNameMapper: [
					[
						'^#spruce/(.*)$',
						'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/.spruce/$1',
					],
				],
				modulePathIgnorePatterns: [],
				name: '4754e2ff2a5985c29465fd58674b1bf1',
				prettierPath: 'prettier',
				resetMocks: false,
				resetModules: false,
				restoreMocks: false,
				rootDir:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api',
				roots: [
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api',
				],
				runner: 'jest-runner',
				setupFiles: [],
				setupFilesAfterEnv: [],
				skipFilter: false,
				slowTestThreshold: 5,
				snapshotSerializers: [],
				testEnvironment:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/jest-environment-node/build/index.js',
				testEnvironmentOptions: {},
				testLocationInResults: false,
				testMatch: ['**/__tests__/**/*.test.js?(x)'],
				testPathIgnorePatterns: [
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/tmp/',
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/src/',
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/',
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/testDirsAndFiles/',
				],
				testRegex: [],
				testRunner:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/jest-jasmine2/build/index.js',
				testURL: 'http://localhost',
				timers: 'real',
				transform: [
					[
						'^.+\\.[jt]sx?$',
						'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/babel-jest/build/index.js',
						{},
					],
				],
				transformIgnorePatterns: ['/node_modules/', '\\.pnp\\.[^\\/]+$'],
				watchPathIgnorePatterns: [],
			},
			hasteFS: {
				_rootDir:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api',
				_files: {},
			},
			moduleMap: {
				duplicates: [],
				map: [
					[
						'spruce-mercury-api',
						{
							g: ['package.json', 1],
						},
					],
				],
				mocks: [],
				rootDir:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api',
			},
			resolver: {
				_options: {
					extensions: ['.js', '.json', '.jsx', '.ts', '.tsx', '.node'],
					hasCoreModules: true,
					moduleDirectories: ['node_modules'],
					moduleNameMapper: [
						{
							moduleName:
								'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/.spruce/$1',
							regex: {},
						},
					],
					rootDir:
						'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api',
				},
				_moduleMap: {
					duplicates: [],
					map: [
						[
							'spruce-mercury-api',
							{
								g: ['package.json', 1],
							},
						],
					],
					mocks: [],
					rootDir:
						'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api',
				},
				_moduleIDCache: {},
				_moduleNameCache: {},
				_modulePathCache: {},
				_supportsNativePlatform: false,
			},
		},
		duration: 0,
		path: `/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/${fileName}`,
	},
	testResult: {
		leaks: false,
		numFailingTests: 0,
		numPassingTests: 35,
		numPendingTests: 1,
		numTodoTests: 0,
		openHandles: [],
		perfStats: {
			end: 1603492715287,
			runtime: 1490,
			slow: false,
			start: 1603492713797,
		},
		skipped: false,
		snapshot: {
			added: 0,
			fileDeleted: false,
			matched: 0,
			unchecked: 0,
			unmatched: 0,
			updated: 0,
			uncheckedKeys: [],
		},
		testFilePath:
			'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/implementation/Database.test.js',
		testResults: [
			{
				ancestorTitles: [],
				duration: 3,
				failureDetails: [],
				failureMessages: [],
				fullName: 'throws error when updating record not found (neDb)',
				location: null,
				numPassingAsserts: 0,
				status: 'passed',
				title: 'throws error when updating record not found (neDb)',
			},
			{
				ancestorTitles: [],
				duration: 57,
				failureDetails: [],
				failureMessages: [],
				fullName: 'throws error when updating record not found (mongo)',
				location: null,
				numPassingAsserts: 0,
				status: 'passed',
				title: 'throws error when updating record not found (mongo)',
			},
			{
				ancestorTitles: [],
				duration: 3,
				failureDetails: [],
				failureMessages: [],
				fullName: 'can upsert against null+undefined undefined -> null (neDb)',
				location: null,
				numPassingAsserts: 0,
				status: 'passed',
				title: 'can upsert against null+undefined undefined -> null (neDb)',
			},
			{
				ancestorTitles: [],
				duration: 0,
				failureDetails: [],
				failureMessages: [],
				fullName: 'can upsert against null+undefined undefined -> null (mongo)',
				location: null,
				numPassingAsserts: 0,
				status: 'pending',
				title: 'can upsert against null+undefined undefined -> null (mongo)',
			},
			{
				ancestorTitles: [],
				duration: 2,
				failureDetails: [],
				failureMessages: [],
				fullName: 'can count (neDb)',
				location: null,
				numPassingAsserts: 0,
				status: 'passed',
				title: 'can count (neDb)',
			},
			{
				ancestorTitles: [],
				duration: 49,
				failureDetails: [],
				failureMessages: [],
				fullName: 'can count (mongo)',
				location: null,
				numPassingAsserts: 0,
				status: 'passed',
				title: 'can count (mongo)',
			},
			{
				ancestorTitles: [],
				duration: 2,
				failureDetails: [],
				failureMessages: [],
				fullName: 'can find by id with $in (neDb)',
				location: null,
				numPassingAsserts: 0,
				status: 'passed',
				title: 'can find by id with $in (neDb)',
			},
			{
				ancestorTitles: [],
				duration: 36,
				failureDetails: [],
				failureMessages: [],
				fullName: 'can find by id with $in (mongo)',
				location: null,
				numPassingAsserts: 0,
				status: 'passed',
				title: 'can find by id with $in (mongo)',
			},
			{
				ancestorTitles: [],
				duration: 4,
				failureDetails: [],
				failureMessages: [],
				fullName:
					'provides helpful duplicate field error with multiple indexes, one at a time (neDb)',
				location: null,
				numPassingAsserts: 0,
				status: 'passed',
				title:
					'provides helpful duplicate field error with multiple indexes, one at a time (neDb)',
			},
			{
				ancestorTitles: [],
				duration: 62,
				failureDetails: [],
				failureMessages: [],
				fullName:
					'provides helpful duplicate field error with multiple indexes, one at a time (mongo)',
				location: null,
				numPassingAsserts: 0,
				status: 'passed',
				title:
					'provides helpful duplicate field error with multiple indexes, one at a time (mongo)',
			},
		],
		failureMessage: null,
	},
	aggregatedResult: {
		numFailedTestSuites: 1,
		numFailedTests: 1,
		numPassedTestSuites: 19,
		numPassedTests: 181,
		numPendingTestSuites: 0,
		numPendingTests: 1,
		numRuntimeErrorTestSuites: 0,
		numTodoTests: 0,
		numTotalTestSuites: 39,
		numTotalTests: 183,
		openHandles: [],
		snapshot: {
			added: 0,
			didUpdate: false,
			failure: false,
			filesAdded: 0,
			filesRemoved: 0,
			filesRemovedList: [],
			filesUnmatched: 0,
			filesUpdated: 0,
			matched: 0,
			total: 0,
			unchecked: 0,
			uncheckedKeysByFile: [],
			unmatched: 0,
			updated: 0,
		},
		startTime: 1603492709248,
		success: false,
		testResults: [
			{
				leaks: false,
				numFailingTests: 0,
				numPassingTests: 4,
				numPendingTests: 0,
				numTodoTests: 0,
				openHandles: [],
				perfStats: {
					end: 1603492711388,
					runtime: 1647,
					slow: false,
					start: 1603492709741,
				},
				skipped: false,
				snapshot: {
					added: 0,
					fileDeleted: false,
					matched: 0,
					unchecked: 0,
					unmatched: 0,
					updated: 0,
					uncheckedKeys: [],
				},
				testFilePath:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/implementation/CasualNameUtility.test.js',
				testResults: [
					{
						ancestorTitles: [],
						duration: 2,
						failureDetails: [],
						failureMessages: [],
						fullName: 'No name returns friend',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'No name returns friend',
					},
					{
						ancestorTitles: [],
						duration: 0,
						failureDetails: [],
						failureMessages: [],
						fullName: 'Just last name to just last name',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'Just last name to just last name',
					},
					{
						ancestorTitles: [],
						duration: 1,
						failureDetails: [],
						failureMessages: [],
						fullName: 'First name only to first name only',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'First name only to first name only',
					},
					{
						ancestorTitles: [],
						duration: 0,
						failureDetails: [],
						failureMessages: [],
						fullName: 'last and first name to First Last initial',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'last and first name to First Last initial',
					},
				],
				failureMessage: null,
			},
			{
				leaks: false,
				numFailingTests: 0,
				numPassingTests: 1,
				numPendingTests: 0,
				numTodoTests: 0,
				openHandles: [],
				perfStats: {
					end: 1603492711854,
					runtime: 452,
					slow: false,
					start: 1603492711402,
				},
				skipped: false,
				snapshot: {
					added: 0,
					fileDeleted: false,
					matched: 0,
					unchecked: 0,
					unmatched: 0,
					updated: 0,
					uncheckedKeys: [],
				},
				testFilePath:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/implementation/PhoneUtility.test.js',
				testResults: [
					{
						ancestorTitles: [],
						duration: 1,
						failureDetails: [],
						failureMessages: [],
						fullName: 'canMatchDummyNumber',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'canMatchDummyNumber',
					},
				],
				failureMessage: null,
			},
			{
				leaks: false,
				numFailingTests: 0,
				numPassingTests: 6,
				numPendingTests: 0,
				numTodoTests: 0,
				openHandles: [],
				perfStats: {
					end: 1603492712140,
					runtime: 278,
					slow: false,
					start: 1603492711862,
				},
				skipped: false,
				snapshot: {
					added: 0,
					fileDeleted: false,
					matched: 0,
					unchecked: 0,
					unmatched: 0,
					updated: 0,
					uncheckedKeys: [],
				},
				testFilePath:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/implementation/TokenUtility.test.js',
				testResults: [
					{
						ancestorTitles: [],
						duration: 0,
						failureDetails: [],
						failureMessages: [],
						fullName: 'exists',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'exists',
					},
					{
						ancestorTitles: [],
						duration: 10,
						failureDetails: [],
						failureMessages: [],
						fullName: 'canGenerateTokenForPerson',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'canGenerateTokenForPerson',
					},
					{
						ancestorTitles: [],
						duration: 1,
						failureDetails: [],
						failureMessages: [],
						fullName: 'generatesValidToken',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'generatesValidToken',
					},
					{
						ancestorTitles: [],
						duration: 1,
						failureDetails: [],
						failureMessages: [],
						fullName: 'decodesAndVerifiesValidToken',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'decodesAndVerifiesValidToken',
					},
					{
						ancestorTitles: [],
						duration: 1,
						failureDetails: [],
						failureMessages: [],
						fullName: 'decodesValidToken',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'decodesValidToken',
					},
					{
						ancestorTitles: [],
						duration: 17,
						failureDetails: [],
						failureMessages: [],
						fullName: 'verifyFailsOnBadSecret',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'verifyFailsOnBadSecret',
					},
				],
				failureMessage: null,
			},
			{
				leaks: false,
				numFailingTests: 0,
				numPassingTests: 2,
				numPendingTests: 0,
				numTodoTests: 0,
				openHandles: [],
				perfStats: {
					end: 1603492712547,
					runtime: 2807,
					slow: false,
					start: 1603492709740,
				},
				skipped: false,
				snapshot: {
					added: 0,
					fileDeleted: false,
					matched: 0,
					unchecked: 0,
					unmatched: 0,
					updated: 0,
					uncheckedKeys: [],
				},
				testFilePath:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/implementation/RoleStore.test.js',
				testResults: [
					{
						ancestorTitles: [],
						duration: 4,
						failureDetails: [],
						failureMessages: [],
						fullName: 'canCreateOrgStore',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'canCreateOrgStore',
					},
					{
						ancestorTitles: [],
						duration: 80,
						failureDetails: [],
						failureMessages: [],
						fullName: 'canGenerateBaseRoles',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'canGenerateBaseRoles',
					},
				],
				failureMessage: null,
			},
			{
				leaks: false,
				numFailingTests: 0,
				numPassingTests: 8,
				numPendingTests: 0,
				numTodoTests: 0,
				openHandles: [],
				perfStats: {
					end: 1603492712756,
					runtime: 3023,
					slow: false,
					start: 1603492709733,
				},
				skipped: false,
				snapshot: {
					added: 0,
					fileDeleted: false,
					matched: 0,
					unchecked: 0,
					unmatched: 0,
					updated: 0,
					uncheckedKeys: [],
				},
				testFilePath:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/implementation/PersonRoleStore.test.js',
				testResults: [
					{
						ancestorTitles: [],
						duration: 6,
						failureDetails: [],
						failureMessages: [],
						fullName: 'personRole',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'personRole',
					},
					{
						ancestorTitles: [],
						duration: 88,
						failureDetails: [],
						failureMessages: [],
						fullName: 'canGivePersonGlobalRole',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'canGivePersonGlobalRole',
					},
					{
						ancestorTitles: [],
						duration: 25,
						failureDetails: [],
						failureMessages: [],
						fullName: 'canGiveRoleAndThenTakeItAway',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'canGiveRoleAndThenTakeItAway',
					},
					{
						ancestorTitles: [],
						duration: 30,
						failureDetails: [],
						failureMessages: [],
						fullName: 'canAssignOrgRole',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'canAssignOrgRole',
					},
					{
						ancestorTitles: [],
						duration: 28,
						failureDetails: [],
						failureMessages: [],
						fullName: 'removeRoleFromOrgDoesNotRemoveGlobal',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'removeRoleFromOrgDoesNotRemoveGlobal',
					},
					{
						ancestorTitles: [],
						duration: 14,
						failureDetails: [],
						failureMessages: [],
						fullName: 'cantAssignSameRoleTwice',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'cantAssignSameRoleTwice',
					},
					{
						ancestorTitles: [],
						duration: 18,
						failureDetails: [],
						failureMessages: [],
						fullName: 'canAddRemoveThenReAddRole',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'canAddRemoveThenReAddRole',
					},
					{
						ancestorTitles: [],
						duration: 19,
						failureDetails: [],
						failureMessages: [],
						fullName: 'removesTheCorrectRole',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'removesTheCorrectRole',
					},
				],
				failureMessage: null,
			},
			{
				leaks: false,
				numFailingTests: 0,
				numPassingTests: 4,
				numPendingTests: 0,
				numTodoTests: 0,
				openHandles: [],
				perfStats: {
					end: 1603492712933,
					runtime: 371,
					slow: false,
					start: 1603492712562,
				},
				skipped: false,
				snapshot: {
					added: 0,
					fileDeleted: false,
					matched: 0,
					unchecked: 0,
					unmatched: 0,
					updated: 0,
					uncheckedKeys: [],
				},
				testFilePath:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/implementation/ContractValidator.test.js',
				testResults: [
					{
						ancestorTitles: [],
						duration: 2,
						failureDetails: [],
						failureMessages: [],
						fullName: 'canRegisterContract',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'canRegisterContract',
					},
					{
						ancestorTitles: [],
						duration: 0,
						failureDetails: [],
						failureMessages: [],
						fullName: 'cannotMixinContractWithDuplicateEvents',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'cannotMixinContractWithDuplicateEvents',
					},
					{
						ancestorTitles: [],
						duration: 1,
						failureDetails: [],
						failureMessages: [],
						fullName: 'canClearEventsFromContract',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'canClearEventsFromContract',
					},
					{
						ancestorTitles: [],
						duration: 1,
						failureDetails: [],
						failureMessages: [],
						fullName: 'clearingUnknownEventThrowsError',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'clearingUnknownEventThrowsError',
					},
				],
				failureMessage: null,
			},
			{
				leaks: false,
				numFailingTests: 0,
				numPassingTests: 2,
				numPendingTests: 0,
				numTodoTests: 0,
				openHandles: [],
				perfStats: {
					end: 1603492712935,
					runtime: 3202,
					slow: false,
					start: 1603492709733,
				},
				skipped: false,
				snapshot: {
					added: 0,
					fileDeleted: false,
					matched: 0,
					unchecked: 0,
					unmatched: 0,
					updated: 0,
					uncheckedKeys: [],
				},
				testFilePath:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/implementation/MercuryServer.test.js',
				testResults: [
					{
						ancestorTitles: [],
						duration: 28,
						failureDetails: [],
						failureMessages: [],
						fullName: 'canCreateServer',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'canCreateServer',
					},
					{
						ancestorTitles: [],
						duration: 21,
						failureDetails: [],
						failureMessages: [],
						fullName: 'throwsWhenEmittingBadEvent',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'throwsWhenEmittingBadEvent',
					},
				],
				failureMessage: null,
			},
			{
				leaks: false,
				numFailingTests: 1,
				numPassingTests: 0,
				numPendingTests: 0,
				numTodoTests: 0,
				openHandles: [],
				perfStats: {
					end: 1603492713171,
					runtime: 3454,
					slow: false,
					start: 1603492709717,
				},
				skipped: false,
				snapshot: {
					added: 0,
					fileDeleted: false,
					matched: 0,
					unchecked: 0,
					unmatched: 0,
					updated: 0,
					uncheckedKeys: [],
				},
				testFilePath:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/behavioral/UpdatingARole.test.js',
				testResults: [
					{
						ancestorTitles: [],
						duration: 24,
						failureDetails: [
							{
								actual: '',
								error: {},
								expected: '',
								matcherName: '',
								message:
									'Error: \n\n\u001b[1mfalse\u001b[22m\n\n does not equal \n\n\u001b[1mtrue\u001b[22m\n\n',
								passed: false,
								stack:
									'Error: \n\n\u001b[1mfalse\u001b[22m\n\n does not equal \n\n\u001b[1mtrue\u001b[22m\n\n\n    at Object.fail (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/@sprucelabs/test/src/utilities/assert.utility.ts:12:9)\n    at Object.isEqual (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/@sprucelabs/test/src/assert.ts:99:9)\n    at Object.assert (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/@sprucelabs/test/src/assert.ts:185:8)\n    at _callee$ (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/src/__tests__/behavioral/UpdatingARole.test.ts:7:3)\n    at new Promise (<anonymous>)\n    at Function.hasUpdateRoleEvent (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/behavioral/UpdatingARole.test.js:92:36)\n    at Object.<anonymous> (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/@sprucelabs/test/src/decorators.ts:36:11)\n    at Object.asyncJestTest (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)\n    at /Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/jest-jasmine2/build/queueRunner.js:45:12\n    at new Promise (<anonymous>)\n    at mapper (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/jest-jasmine2/build/queueRunner.js:28:19)\n    at /Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/jest-jasmine2/build/queueRunner.js:75:41',
							},
						],
						failureMessages: [
							'Error: \n\n\u001b[1mfalse\u001b[22m\n\n does not equal \n\n\u001b[1mtrue\u001b[22m\n\n\n    at Object.fail (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/@sprucelabs/test/src/utilities/assert.utility.ts:12:9)\n    at Object.isEqual (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/@sprucelabs/test/src/assert.ts:99:9)\n    at Object.assert (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/@sprucelabs/test/src/assert.ts:185:8)\n    at _callee$ (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/src/__tests__/behavioral/UpdatingARole.test.ts:7:3)\n    at new Promise (<anonymous>)\n    at Function.hasUpdateRoleEvent (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/behavioral/UpdatingARole.test.js:92:36)\n    at Object.<anonymous> (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/@sprucelabs/test/src/decorators.ts:36:11)\n    at Object.asyncJestTest (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)\n    at /Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/jest-jasmine2/build/queueRunner.js:45:12\n    at new Promise (<anonymous>)\n    at mapper (/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/jest-jasmine2/build/queueRunner.js:28:19)\n    at /Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/node_modules/jest-jasmine2/build/queueRunner.js:75:41',
						],
						fullName: 'hasUpdateRoleEvent',
						location: null,
						numPassingAsserts: 0,
						status: 'failed',
						title: 'hasUpdateRoleEvent',
					},
				],
				failureMessage:
					'\u001b[1m\u001b[31m  \u001b[1m● \u001b[22m\u001b[1mhasUpdateRoleEvent\u001b[39m\u001b[22m\n\n\n\n    \u001b[1mfalse\u001b[22m\n\n     does not equal \n\n    \u001b[1mtrue\u001b[22m\n\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.fail (\u001b[22m\u001b[2mnode_modules/@sprucelabs/test/src/utilities/assert.utility.ts\u001b[2m:12:9)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.isEqual (\u001b[22m\u001b[2mnode_modules/@sprucelabs/test/src/assert.ts\u001b[2m:99:9)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.assert (\u001b[22m\u001b[2mnode_modules/@sprucelabs/test/src/assert.ts\u001b[2m:185:8)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat _callee$ (\u001b[22m\u001b[2msrc/__tests__/behavioral/UpdatingARole.test.ts\u001b[2m:7:3)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Function.hasUpdateRoleEvent (\u001b[22m\u001b[2m\u001b[0m\u001b[36mbuild/__tests__/behavioral/UpdatingARole.test.js\u001b[39m\u001b[0m\u001b[2m:92:36)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.<anonymous> (\u001b[22m\u001b[2mnode_modules/@sprucelabs/test/src/decorators.ts\u001b[2m:36:11)\u001b[22m\u001b[2m\u001b[22m\n',
			},
			{
				leaks: false,
				numFailingTests: 0,
				numPassingTests: 2,
				numPendingTests: 0,
				numTodoTests: 0,
				openHandles: [],
				perfStats: {
					end: 1603492714157,
					runtime: 274,
					slow: false,
					start: 1603492713883,
				},
				skipped: false,
				snapshot: {
					added: 0,
					fileDeleted: false,
					matched: 0,
					unchecked: 0,
					unmatched: 0,
					updated: 0,
					uncheckedKeys: [],
				},
				testFilePath:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/implementation/SkillGenerator.test.js',
				testResults: [
					{
						ancestorTitles: [],
						duration: 1,
						failureDetails: [],
						failureMessages: [],
						fullName: 'canInstantiate',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'canInstantiate',
					},
					{
						ancestorTitles: [],
						duration: 1,
						failureDetails: [],
						failureMessages: [],
						fullName: 'generatesNewSkillValuesByName',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'generatesNewSkillValuesByName',
					},
				],
				failureMessage: null,
			},
			{
				leaks: false,
				numFailingTests: 0,
				numPassingTests: 35,
				numPendingTests: 1,
				numTodoTests: 0,
				openHandles: [],
				perfStats: {
					end: 1603492715287,
					runtime: 1490,
					slow: false,
					start: 1603492713797,
				},
				skipped: false,
				snapshot: {
					added: 0,
					fileDeleted: false,
					matched: 0,
					unchecked: 0,
					unmatched: 0,
					updated: 0,
					uncheckedKeys: [],
				},
				testFilePath:
					'/Users/taylorromero/Development/SpruceLabs/spruce-mercury-api/build/__tests__/implementation/Database.test.js',
				testResults: [
					{
						ancestorTitles: [],
						duration: 3,
						failureDetails: [],
						failureMessages: [],
						fullName: 'throws error when updating record not found (neDb)',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'throws error when updating record not found (neDb)',
					},
					{
						ancestorTitles: [],
						duration: 47,
						failureDetails: [],
						failureMessages: [],
						fullName: 'can delete record (mongo)',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'can delete record (mongo)',
					},
					{
						ancestorTitles: [],
						duration: 5,
						failureDetails: [],
						failureMessages: [],
						fullName: 'can upsert (neDb)',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'can upsert (neDb)',
					},
					{
						ancestorTitles: [],
						duration: 82,
						failureDetails: [],
						failureMessages: [],
						fullName: 'can create a compound field unique index (mongo)',
						location: null,
						numPassingAsserts: 0,
						status: 'passed',
						title: 'can create a compound field unique index (mongo)',
					},
				],
				failureMessage: null,
			},
		],
		wasInterrupted: false,
	},
})

export default onTestFileResult
