// Fixes path alias not working in code generated by "tsc"
// Based on https://gist.github.com/deejayy/aa5f0cde76dc29f6b4127e60e74be2f2
import customModuleLoader = require('module');
import path = require('path')

class CustomModuleLoader {
  public cOptions: any = require('../../tsconfig.json').compilerOptions;

  public replacePaths: any = {};

  constructor() {
    Object.keys(this.cOptions.paths).forEach(alias => {
      this.replacePaths[alias.replace(/\*.?/, '(.*)')] = this.cOptions.paths[alias][0].replace(/\*.?/, '$1');
    });

    (<any>customModuleLoader)._originalResolveFilename = (<any>customModuleLoader)._resolveFilename;

    (<any>customModuleLoader)._resolveFilename = (request: string, parent: customModuleLoader, isMain: boolean) => {
      Object.keys(this.replacePaths).forEach(matchString => {
        let regex = new RegExp(matchString);
        if (request.match(regex)) {
					const mapped = this.replacePaths[matchString]
					// are we being mapped to something in node_modules?
					if (mapped.search('node_modules') > -1) {
						request = path.join(__dirname,'..','..', request.replace(regex,mapped))
					} else {
						request = path.join(__dirname,'..','..', this.cOptions.outDir, request.replace(regex,mapped))
					}
        }
      })
      return (<any>customModuleLoader)._originalResolveFilename(request, parent, isMain);
    }
  }
};

new CustomModuleLoader()
